### PR TITLE
1.0.0rc0

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
Please make sure to squash this when you merge it in!
The tricks are this file:

recipe/conda_build_config.yaml

which tells conda-forge to upload the package to `conda-forge/label/gufe_rc` 

and the target branch for the PR is not `main` but `rc`

**Comment by mikemhenry** [comment]
Then it gets installed like this:
`conda install -c conda-forge/label/gufe_rc -c conda-forge gufe`

**Comment by mikemhenry** [comment]
This line https://github.com/conda-forge/gufe-feedstock/pull/35/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR10 will need to be updated either to the tag or commit you want to use for the rc

**Comment by mikemhenry** [comment]
@conda-forge-admin, please rerender

**Review by richardjgowers — APPROVED** [review]

**Pull request merged**
