### PR TITLE
Release 0.9.5

### PR DESCRIPTION
**Pull request by richardjgowers**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by richardjgowers** [comment]
@conda-forge-admin, please rerender

**Review by IAlibay — APPROVED** [review]

**Comment by mikemhenry** [comment]
@richardjgowers when you do these PRs by hand (aka artisanal) I recommend you use a branch off of your fork that isn't `main` 

@conda-forge-admin, please restart ci

**Comment by richardjgowers** [comment]
@mikemhenry what would be different?

**Comment by mikemhenry** [comment]
Now your `main` branch won't match the `upstream main` when these commits get squashed and merged in. It is mostly a housekeeping thing that will prevent history getting weird, since if you forget to checkout `upstream/main` when making changes, you will end up adding extra commits. I try and keep `origin/main` and `upstream/main` in sync, and the only practical way to do that (since someone might in a larger project get a PR merged in before mine) is to not use the `main` branch of of a fork.

Does that make sense? I think in some cases, like if we didn't squash commits here, it would stay in sync, so it might not make a difference in this case, but if you always do the same thing regardless of the case, then you don't need to worry if it is a special case or not.

**Comment by mikemhenry** [comment]
`Command '['/opt/conda/bin/git', 'checkout', 'v0.9.5']' returned non-zero exit status 1.`
`checkout: 'v0.9.5'`
image
The tag is missing the `v` so you need to either remake the tag or change the meta.yaml and remove the `v`

**Pull request merged**
